# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
#field is what tells GitHub Actions when to run. In this case, we're running the workflow anytime there's a pus

jobs:
  build:
#our template workflow defines a single job with the identifier build
    name: CI node action
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016]
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
  #used to ensure our virtual machine has a copy of our codebase. The checked out code will be used to run tests against.
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
  #used to set up proper versions of Node.js since we'll be performing testing against multiple versions.
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
#Workflow: A workflow is a unit of automation from start to finish, including the definition of what triggers the automation, what environment or other aspects should be taken account during the automation, and what should happen as a result of the trigger.
#Job: A job is a section of the workflow, and is made up of one or more steps. In this section of our workflow, the template defines the steps that make up the build job.
#Step: A step represents one effect of the automation. A step could be defined as a GitHub Action, or another unit, like printing something to the console.
#Action: A GitHub Action is a piece of automation written in a way that is compatible with workflows. Actions can be written by GitHub, by the open source community, or you can write them yourself!
